language: python

python:
  - 2.7

before_install: pip install itsdangerous simplejson Flask-Mail

script: python setup.py test

branches:
  except:
    - website

notifications:
  # Disable travis notifications until they figured out how to hide
  # their own builder failure from us.  Travis currently fails way
  # too many times by itself.
  email: true
